title: Einfache Seite
icon: page

tabs:
  content:
    sections:
      fieldsmain:
        type: fields
        fields:
          headline:
            label: Meine H1
            type: text
          text:
            label: Kompletter Text
            type: textarea
            size: large
  seo: seo/page